### ISSUE TITLE
Fails with a var object literal statement

### ISSUE THREAD

**Issue by pgilad** [Olical/vim-expand#1]
``` js
    var templates{1,2} = {
        jmeter: 'tests_jmxTestForm',
        http: 'tests_httpTestForm',
        webdriver: 'tests_webdriverTestForm'
    };
```

`:Expand` on region:

``` js
    var templates1 = 
        jmeter: 'tests_jmxTestForm';
    var templates1 = 
        http: 'tests_httpTestForm';
    var templates1 = 
        webdriver: 'tests_webdriverTestForm'
    ;
    var templates2 = 
        jmeter: 'tests_jmxTestForm';
    var templates2 = 
        http: 'tests_httpTestForm';
    var templates2 = 
        webdriver: 'tests_webdriverTestForm'
    ;
```

**Comment by Olical** [comment]
Stuff like...

``` javascript
var templates{1,2} = [
    'tests_jmxTestForm',
    'tests_httpTestForm',
    'tests_webdriverTestForm'
];
```

Works fine, so I presume it's to do with the second occurrence of curly braces. I'm cheating at the moment by using the built in `expand` function, maybe this means I need to write my own that's cross platform and will be more predictable. That would allow addition of new features too.

Thanks for pointing out a case where it completely falls over, I'll see what I can do soon.

**Comment by Olical** [comment]
Closing this since I feel like it's just been left open for too long and will remain that way. I'm not sure if I'll ever get around to fixing it, it's a simple plugin that's sort of okay at one job. Admittedly it has many flaws such as this though :)
